### ISSUE TITLE
Diagram: Meta Issue

### ISSUE THREAD

**Issue by slisson** [mbeddr/mbeddr.core#1465]
In this issue, the priorities for the Diagram related issues are maintained. Issues at the top get fixed first.

Cell layout/Embedded Cells
- [ ] #1467 Auto layout option moves the contents of boxes (it should not) comp.diagram (see #1411)
- [ ] #1456 Should be able to adjust spacing/padding of box contents. (1d)
- [ ] #1414 Diagrams: Buttons overlap with content (0.5h)
- [ ] #1419 Toolbar does not always show completely (0.25h)
- [ ] #1466 Borders inside boxes don't work correctly. (1d)
- [ ] #1464 Diagram: Allow shapes to reserve additional space (4h)
- [ ] #1411 Subdiagrams are outside their box after autolayout and zoom (2d)

Diagram/Auto Layout
- [ ] #1424 Diagram: Loop edges cannot be layouted (4h)

Synchronization
- [ ] #1417 Deleting a node reference in diagram editor reinstitues old reference instead of deleting it (1d)
- [ ] #1421 When cloning a model with a graphical editor, layout is not preserved (1d)

Nodes visible in multiple diagrams
- [x] #1470 Allow nodes to be visible in multiple diagrams 
- [ ] #1472 Allow to specify read-only in nodesQeury
- [x]  #1471 Be able to distinguish in which context a node is displayed in the diagram editor

Other
- [x] #1446 Drag & Drop features for the graphical editor (3d)
- [x] #1455 Should be able to set the background color of the diagram (0.25h)
- [ ] #1451 Diagram: Set focus to the editor after drop from palette (0.25h)
- [ ] #1452 Selection and navigation in diagrams is unexpected (Case 1/2: 0.25h; Case 3/4: default MPS navigation behavior, hard to change)
- [x] #1428 Colors in diagram editor definition not legible (not part of the framework)
- [ ] #1469 Code generated for "if" in shape property results in cast error

**Comment by slisson** [comment]
@joswarmer I added time estimates

**Comment by kbirken** [comment]
Kamino closed and cloned this issue to [JetBrains/MPS-extensions](https://github.com/JetBrains/MPS-extensions/issues/80)
